use std::collections::HashSet;

// curated from disconnect.me tracking-protection + major ad networks
const BLOCKED_DOMAINS: &[&str] = &[
    // google ads/tracking
    "doubleclick.net",
    "googlesyndication.com",
    "googleadservices.com",
    "google-analytics.com",
    "googletagmanager.com",
    "googletagservices.com",
    "pagead2.googlesyndication.com",
    "adservice.google.com",
    "2mdn.net",
    "admob.com",
    "app-measurement.com",
    "crashlytics.com",
    "firebaselogging.googleapis.com",
    // facebook tracking
    "facebook.net",
    "fbcdn.net",
    "pixel.facebook.com",
    "an.facebook.com",
    "connect.facebook.net",
    // amazon ads
    "amazon-adsystem.com",
    "aax.amazon-adsystem.com",
    "mads.amazon-adsystem.com",
    // major ad exchanges
    "adnxs.com",
    "adsrvr.org",
    "criteo.com",
    "criteo.net",
    "rubiconproject.com",
    "pubmatic.com",
    "openx.net",
    "casalemedia.com",
    "indexww.com",
    "3lift.com",
    "triplelift.com",
    "sharethrough.com",
    "smartadserver.com",
    "yieldmo.com",
    "33across.com",
    "sovrn.com",
    "lijit.com",
    "gumgum.com",
    "bidswitch.net",
    "adform.net",
    "contextweb.com",
    "conversantmedia.com",
    "spotxchange.com",
    "spotx.tv",
    "richaudience.com",
    "synacor.com",
    "e-planning.net",
    "undertone.com",
    "yldbt.com",
    "rhythmone.com",
    "unrulymedia.com",
    "districtm.io",
    "nobid.io",
    "brightcom.com",
    // tracking/analytics
    "hotjar.com",
    "mixpanel.com",
    "segment.io",
    "segment.com",
    "amplitude.com",
    "newrelic.com",
    "nr-data.net",
    "optimizely.com",
    "crazyegg.com",
    "mouseflow.com",
    "fullstory.com",
    "clicktale.net",
    "heapanalytics.com",
    "luckyorange.com",
    "inspectlet.com",
    "logrocket.com",
    "smartlook.com",
    "contentsquare.net",
    "clarity.ms",
    "demdex.net",
    "bluekai.com",
    "exelator.com",
    "krxd.net",
    "scorecardresearch.com",
    "quantserve.com",
    "comscore.com",
    "rlcdn.com",
    "liveramp.com",
    "tapad.com",
    "agkn.com",
    "eyeota.net",
    "1rx.io",
    "intentiq.com",
    "id5-sync.com",
    "liadm.com",
    "adsymptotic.com",
    "brealtime.com",
    "mathtag.com",
    "mookie1.com",
    "myvisualiq.net",
    "pippio.com",
    "qs.ioam.de",
    "revcontent.com",
    "serving-sys.com",
    "smaato.net",
    // content recommendation (outbrain/taboola)
    "outbrain.com",
    "outbrainimg.com",
    "taboola.com",
    "taboolasyndication.com",
    "zemanta.com",
    "mgid.com",
    "contentad.net",
    "revcontent.com",
    "adblade.com",
    // video ads
    "moatads.com",
    "moatpixel.com",
    "doubleverify.com",
    "ias.com",
    "iasds01.com",
    "integralads.com",
    "aniview.com",
    "springserve.com",
    "jwpltx.com",
    "connatix.com",
    "primis.tech",
    "vidoomy.com",
    // social trackers
    "platform.twitter.com",
    "syndication.twitter.com",
    "analytics.twitter.com",
    "ads-twitter.com",
    "platform.linkedin.com",
    "snap.licdn.com",
    "ads.linkedin.com",
    "sc-static.net",
    "tr.snapchat.com",
    "ads.pinterest.com",
    "trk.pinterest.com",
    "analytics.tiktok.com",
    "ads.tiktok.com",
    // adware/popups
    "popads.net",
    "popcash.net",
    "propellerads.com",
    "juicyads.com",
    "exoclick.com",
    "trafficjunky.com",
    "clickadu.com",
    "hilltopads.com",
    "adsterra.com",
    "bidvertiser.com",
    "revenuehits.com",
    "adcash.com",
    "trafficfactory.biz",
    // youtube specific
    "youtube.ad.network",
    "youtubei.googleapis.com",
    "pagead2.googlesyndication.com",
    "tpc.googlesyndication.com",
    "static.doubleclick.net",
    "ad.doubleclick.net",
    "ads.youtube.com",
    "yt3.ggpht.com",
    // adult site ads
    "trafficstars.com",
    "tsyndicate.com",
    "exosrv.com",
    "realsrv.com",
    "a.realsrv.com",
    "mc.yandex.ru",
    "syndication.exoclick.com",
    "main.exoclick.com",
    "static.exoclick.com",
    "ads.exoclick.com",
    "adsco.re",
    "awempire.com",
    "cpmstar.com",
    "plugrush.com",
    "ad.plus",
    "tsyndicate.com",
    "jads.co",
    "etahub.com",
    "ero-advertising.com",
    "adxpansion.com",
    "padsdel.com",
    "clicads.com",
    // cookie/consent trackers (ironic)
    "cookielaw.org",
    "cookiebot.com",
    "cookiepro.com",
    // fingerprinting
    "fingerprintjs.com",
    "fpjs.io",
    // misc trackers
    "branch.io",
    "app.link",
    "adjust.com",
    "appsflyer.com",
    "kochava.com",
    "singular.net",
    "tenjin.io",
    "chartbeat.com",
    "chartbeat.net",
    "parsely.com",
    "parse.ly",
    "omtrdc.net",
    "omniture.com",
    "2o7.net",
    "demdex.net",
    "everesttech.net",
    "scene7.com",
    "coremetrics.com",
    "imrworldwide.com",
    "effectivemeasure.net",
    "gemius.pl",
    "mediaplex.com",
    "atdmt.com",
    "mxpnl.com",
    "marketo.net",
    "marketo.com",
    "hubspot.com",
    "hsforms.com",
    "hsforms.net",
    "pardot.com",
    "eloqua.com",
    "bizible.com",
    "6sc.co",
    "demandbase.com",
    "bombora.com",
    "bidable.com",
    "company-target.com",
    "dnstats.net",
    "zqtk.net",
    "mfadsrvr.com",
    "ml314.com",
    "ipredictive.com",
    "adgrx.com",
    "adlightning.com",
    "adsafeprotected.com",
    "cdn-messes.com",
    "go-mpulse.net",
    "betweendigital.com",
    "cloudflareinsights.com",
    "statcounter.com",
    "histats.com",
    "sitemeter.com",
    "webtrends.com",
    "alexametrics.com",
    "yandex.ru",
    "mc.yandex.ru",
    "top-fwz1.mail.ru",
    "doubleclick.com",
    "adroll.com",
    "steelhousemedia.com",
    "retargetly.com",
    "adacado.com",
    "rtbhouse.com",
    "sociomantic.com",
    "teads.tv",
    "verizonmedia.com",
    "oath.com",
    "advertising.com",
    "nexage.com",
    "millenialmedia.com",
    "supersonicads.com",
    "unityads.unity3d.com",
    "chartboost.com",
    "vungle.com",
    "applovin.com",
    "inmobi.com",
    "mopub.com",
    "flurry.com",
    "startapp.com",
    "avocarrot.com",
    "fyber.com",
    "tapjoy.com",
    "ironsrc.com",
    "is.com",
    "ad-delivery.net",
    "adcolony.com",
    "aerserv.com",
    "inner-active.com",
    "leadbolt.com",
    "loopme.com",
    "mobfox.com",
    "mintegral.com",
    "ogury.com",
    "smaato.com",
    "verve.com",
    "pubnative.net",
];

pub struct Blocker {
    domains: HashSet<String>,
}

impl Blocker {
    pub fn new() -> Self {
        let domains: HashSet<String> = BLOCKED_DOMAINS.iter().map(|d| d.to_lowercase()).collect();
        Self { domains }
    }

    pub fn to_js_set(&self) -> String {
        let entries: Vec<String> = self.domains.iter().map(|d| format!("\"{}\"", d)).collect();
        format!("new Set([{}])", entries.join(","))
    }

    pub fn domains_clone(&self) -> HashSet<String> {
        self.domains.clone()
    }
}
